2017-03-19 10:32:46 database: flush
org.h2.message.DbException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:188)
	at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:159)
	at GUI.ConnectionFactory.getH2Connection(ConnectionFactory.java:24)
	at GUI.ConnectionFactory.main(ConnectionFactory.java:32)
Caused by: org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-03-19 11:02:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER TABLE PEOPLE 
MODIFY COLUMN PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "
Syntax error in SQL statement "ALTER TABLE PEOPLE 
MODIFY COLUMN PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "; SQL statement:
ALTER TABLE people 
MODIFY COLUMN PERSON_ID int(10) PRIMARY KEY AUTO_INCREMENT [42000-194]
2017-03-19 11:03:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER TABLE PEOPLE 
MODIFY PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "
Syntax error in SQL statement "ALTER TABLE PEOPLE 
MODIFY PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "; SQL statement:
ALTER TABLE people 
MODIFY PERSON_ID int(10) PRIMARY KEY AUTO_INCREMENT [42000-194]
2017-03-19 11:03:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unbekannter Datentyp: "("
Unknown data type: "("; SQL statement:
ALTER TABLE people 
MODIFY PERSON_ID (int(10) PRIMARY KEY AUTO_INCREMENT) [50004-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4144)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3994)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:5770)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5657)
	at org.h2.command.Parser.parseAlter(Parser.java:4920)
	at org.h2.command.Parser.parsePrepared(Parser.java:346)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:04:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "
Syntax error in SQL statement "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY AUTO_INCREMENT "; SQL statement:
ALTER TABLE people 
ALTER COLUMN PERSON_ID int(10) PRIMARY KEY AUTO_INCREMENT [42000-194]
2017-03-19 11:04:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY  SET AUTO_INCREMENT "
Syntax error in SQL statement "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY  SET AUTO_INCREMENT "; SQL statement:
ALTER TABLE people 
ALTER COLUMN PERSON_ID int(10) PRIMARY KEY  SET AUTO_INCREMENT [42000-194]
2017-03-19 11:06:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY NOT NULL AUTO_INCREMENT "
Syntax error in SQL statement "ALTER TABLE PEOPLE 
ALTER COLUMN PERSON_ID INT(10) PRIMARY[*] KEY NOT NULL AUTO_INCREMENT "; SQL statement:
ALTER TABLE people 
ALTER COLUMN PERSON_ID int(10) PRIMARY KEY not null AUTO_INCREMENT [42000-194]
2017-03-19 11:07:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
insert into people values (
"thorsten",
"böse"
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:08:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
insert into people values (
firstname = "thorsten",
lastname = "böse"
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:08:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "thorsten" nicht gefunden
Column "thorsten" not found; SQL statement:
insert into people (firstname, lastname) values (
"thorsten",
"böse"
) [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:146)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:09:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
insert into people values (
1,"thorsten"
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:13:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO PEOPLE VALUES (1, 'thorsten') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:13:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO PEOPLE VALUES (2, 'thorsten') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:14:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO PEOPLE VALUES ('thorsten', 'böse', 18, ) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:15:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO PEOPLE VALUES ('thorsten', 'böse', 18, 'testwei', 23232, 'gogo', 'male', 'fdfdf', 'dfdf', 'gdgdfd', 'dfdfd') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 11:19:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO PEOPLE VALUES ('thorsten', 'böse', 18, 'testwei', 23232, 'gogo', 'male', 'fdfdf', 'dfdf', 'gdgdfd', 'dfdfd') [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-03-19 12:52:57 database: flush
org.h2.message.DbException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:188)
	at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:159)
	at GUI.ConnectionFactory.getH2Connection(ConnectionFactory.java:24)
	at GUI.ConnectionFactory.main(ConnectionFactory.java:32)
Caused by: org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
2017-03-19 12:54:43 database: flush
org.h2.message.DbException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:188)
	at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:159)
	at GUI.ConnectionFactory.getH2Connection(ConnectionFactory.java:24)
	at GUI.ConnectionFactory.main(ConnectionFactory.java:33)
Caused by: org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/jonasd-wpm/workspace/AE07/AE07_Cupid/database/PeopleOfTheDatabase.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 20 more
